# Generated by Django 5.2.3 on 2025-07-01 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Completed', 'Выполнено'), ('Waiting', 'В ожидании'), ('Deleted', 'Удалено')], default='В ожидании', max_length=100, verbose_name='Статус задачи'),
        ),
    ]
